# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:slim
    #build: .
    ports:
      - 8181:8181
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
